package telemetry

import "context"

type correlationKey struct{}

// WithCorrelationID carries an ID freshly generated by the server request
// boundary, never an incoming header or other client-supplied metadata. Invalid
// values mask inherited IDs; correlation is diagnostic, not authorization.
func WithCorrelationID(ctx context.Context, id string) context.Context {
	if ctx == nil {
		return nil
	}
	if !validCorrelationID(id) {
		id = ""
	}
	return context.WithValue(ctx, correlationKey{}, id)
}

// CorrelationID returns only bounded server request metadata. Non-HTTP callers
// may have no correlation; their authorization and denial evidence still apply.
func CorrelationID(ctx context.Context) string {
	if ctx == nil {
		return ""
	}
	id, _ := ctx.Value(correlationKey{}).(string)
	if !validCorrelationID(id) {
		return ""
	}
	return id
}

func validCorrelationID(id string) bool {
	if len(id) != 32 {
		return false
	}
	for i := range id {
		if (id[i] < '0' || id[i] > '9') && (id[i] < 'a' || id[i] > 'f') {
			return false
		}
	}
	return true
}
